name: Better Leveling
version: 1.0
main: me.monstuhs.betterleveling.BetterLeveling
description: Factors player level into a number of Minecraft activities.
author: monstuhs
commands:
   stats:
      description: Show your currents stats
      usage: /<command>
